# Generated by Django 3.1.6 on 2021-02-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='The club description goes here')),
                ('licence_no', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=10, null=True)),
                ('seats', models.IntegerField(null=True)),
                ('taken', models.BooleanField(default=False)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='foods_menu',
            fields=[
                ('foods_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/')),
                ('description', models.TextField(default='The food description goes here')),
                ('price', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.foods_menu')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/')),
                ('description', models.TextField(default='The event description goes here')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='drinks_menu',
            fields=[
                ('drinks_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='drink',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/')),
                ('description', models.TextField(default='The food description goes here')),
                ('price', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.drinks_menu')),
            ],
        ),
    ]
