# Generated by Django 3.1.6 on 2021-03-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20210216_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks_menu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='foods_menu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
